services:
  photo-portfolio:
    container_name: photo-portfolio
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
  
